name: Docker Image CI

on:
  push:
    tags: [ "v*-py" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gaarf-py

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Format image tag
        run: |
          IMAGE_TAGS=${{ steps.meta.outputs.tags }}
          IMAGE_TAGS="${IMAGE_TAG//-py/}"
          IMAGE_TAGS=($(for IMAGE_TAG in "${IMAGE_TAGS[@]}"; do echo "${IMAGE_TAG//-py/}"; done))
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: py/.
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
